Assignment #2 

Author: Kevin Dumitrescu

Date: February 19, 2022

Class: CS595A Artificial Intelligence

Description: For this assignment, the wine data set must first be imported. This was done through the use of reading the csv file. Afterwards, I then began to analyze the imported data set by first outputting the shape of the data set, through the shape function call; then I looked at the minimum, maximum, and average values for each feature and target label for the data set, through the describe function call; lastly I then implemented a scatter matrix to determine if any of the features strongly correlate amongst each other, through the scatter_matrix function call on the imported data set that has an adjustable window to better see the whole matrix. Once this analysis was concluded, I then split and preprocessed the data to ensure that all values can be processed by for the two multi-class classification configurations of K-Nearest Neighbors and Logistic Regression.

Importing the Wine dataset along with all the necessary libraries 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from pandas.plotting import scatter_matrix
%matplotlib notebook

wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header = None)

Outputting the dataset as a whole with properly assigned column headings

In [3]:
wine.columns = ['Classes', 'Alcohol', 'Malic Acid', 'Ash', 'Alcalinity of Ash', 'Magnesium', 'Total phenols', 'Flavanoids', 
                'Nonflavoids phenols', 'Proanthocyanins', 'Color Intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']
wine

Classes  Alcohol  Malic Acid   Ash  Alcalinity of Ash  Magnesium  \
0          1    14.23        1.71  2.43               15.6        127   
1          1    13.20        1.78  2.14               11.2        100   
2          1    13.16        2.36  2.67               18.6        101   
3          1    14.37        1.95  2.50               16.8        113   
4          1    13.24        2.59  2.87               21.0        118   
..       ...      ...         ...   ...                ...        ...   
173        3    13.71        5.65  2.45               20.5         95   
174        3    13.40        3.91  2.48               23.0        102   
175        3    13.27        4.28  2.26               20.0        120   
176        3    13.17        2.59  2.37               20.0        120   
177        3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavoids phenols  Proanthocyanins  \
0             2.80        3.06                 0.28             2.29   
1             2.65        2.76                 0.26             1.28   
2             2.80        3.24                 0.30             2.81   
3             3.85        3.49                 0.24             2.18   
4             2.80        2.69                 0.39             1.82   
..             ...         ...                  ...              ...   
173           1.68        0.61                 0.52             1.06   
174           1.80        0.75                 0.43             1.41   
175           1.59        0.69                 0.43             1.35   
176           1.65        0.68                 0.53             1.46   
177           2.05        0.76                 0.56             1.35   

     Color Intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

Outputting the shape on the wine dataset via the shape function call on the dataset

In [4]:
wine.shape

(178, 14)

Displaying the min, max, and average values for the feature names and target labels via the use of the describe function

In [5]:
wine.describe()

Classes     Alcohol  Malic Acid         Ash  Alcalinity of Ash  \
count  178.000000  178.000000  178.000000  178.000000         178.000000   
mean     1.938202   13.000618    2.336348    2.366517          19.494944   
std      0.775035    0.811827    1.117146    0.274344           3.339564   
min      1.000000   11.030000    0.740000    1.360000          10.600000   
25%      1.000000   12.362500    1.602500    2.210000          17.200000   
50%      2.000000   13.050000    1.865000    2.360000          19.500000   
75%      3.000000   13.677500    3.082500    2.557500          21.500000   
max      3.000000   14.830000    5.800000    3.230000          30.000000   

        Magnesium  Total phenols  Flavanoids  Nonflavoids phenols  \
count  178.000000     178.000000  178.000000           178.000000   
mean    99.741573       2.295112    2.029270             0.361854   
std     14.282484       0.625851    0.998859             0.124453   
min     70.000000       0.980000    0.340000             0.130000   
25%     88.000000       1.742500    1.205000             0.270000   
50%     98.000000       2.355000    2.135000             0.340000   
75%    107.000000       2.800000    2.875000             0.437500   
max    162.000000       3.880000    5.080000             0.660000   

       Proanthocyanins  Color Intensity         Hue  \
count       178.000000       178.000000  178.000000   
mean          1.590899         5.058090    0.957449   
std           0.572359         2.318286    0.228572   
min           0.410000         1.280000    0.480000   
25%           1.250000         3.220000    0.782500   
50%           1.555000         4.690000    0.965000   
75%           1.950000         6.200000    1.120000   
max           3.580000        13.000000    1.710000   

       OD280/OD315 of diluted wines      Proline  
count                    178.000000   178.000000  
mean                       2.611685   746.893258  
std                        0.709990   314.907474  
min                        1.270000   278.000000  
25%                        1.937500   500.500000  
50%                        2.780000   673.500000  
75%                        3.170000   985.000000  
max                        4.000000  1680.000000

Displaying the scatter matrix for the given dataset using the scatter_matrix function call with a configured and adjustable plot window

In [ ]:
scatter_matrix(wine)
fig = plt.figure(figsize=(10000,10000), dpi=200, facecolor='w', edgecolor='k')
plt.show()

Training the dataset first by spliting the data

In [8]:
variables = wine.values
x = variables[:, 1:13]
y = variables[:, 0]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(142, 12) (36, 12) (142,) (36,)


Preprocessing the dataset

In [9]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

K-Nearest Neighbors Implementation

In [18]:
perceptor = KNeighborsClassifier(n_neighbors=3)
perceptor.fit(x_train, y_train)
y_pred =perceptor.predict(x_test)
print("Confusion Matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("\nAccuracy score: \n" + str(accuracy_score(y_test, y_pred)))
print("\nPerformance Statistics: \n" + str(classification_report(y_test, y_pred)))
plt.show(perceptor)

Confusion Matrix: 
[[14  0  0]
 [ 1 12  0]
 [ 0  0  9]]

Accuracy score: 
0.9722222222222222

Performance Statistics: 
              precision    recall  f1-score   support

         1.0       0.93      1.00      0.97        14
         2.0       1.00      0.92      0.96        13
         3.0       1.00      1.00      1.00         9

    accuracy                           0.97        36
   macro avg       0.98      0.97      0.98        36
weighted avg       0.97      0.97      0.97        36



Logistic Regression Implementation

In [16]:
perceptor = LogisticRegression(C=100, max_iter=1500, random_state=1)
perceptor.fit(x_train, y_train)
y_pred =perceptor.predict(x_test)
print("Confusion Matrix: \n" + str(confusion_matrix(y_test, y_pred)))
print("\nAccuracy score: \n" + str(accuracy_score(y_test, y_pred)))
print("\nPerformance statstics: \n" + str(classification_report(y_test, y_pred)))

Confusion Matrix: 
[[14  0  0]
 [ 0 13  0]
 [ 0  0  9]]

Accuracy score: 
1.0

Performance statstics: 
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        14
         2.0       1.00      1.00      1.00        13
         3.0       1.00      1.00      1.00         9

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

